name: Bump Package Version

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]

jobs:
  increment_version:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Run merge script
      run: |
        echo PR #${{ github.event.number }} has been merged
        mvn versions:set -DnewVersion=0.1.2-SNAPSHOT
    - name: Commit new pom version
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Bump commit version