name: Release

# Trigger on push to branch with 'release in name'
on:
  push:
    branches:
      - '*release*'

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - name: Tag release commit and push release package
        run: mvn -B -U --no-transfer-progress release:prepare release:perform
      - name: Get tag version to create release
        run: |
          TAG=$(git describe --abbrev=0 --tags)
          echo "TAG=$TAG" >> $GITHUB_ENV
          TAG_VERSION=`echo $TAG | cut -d v -f 2`
          echo "TAG_VERSION=$TAG_VERSIOn" >> $GITHUB_ENV
      - name: Create Github release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: ${{ env.TAG_VERSION }}
          body: |
            Just testing
          draft: false
          prerelease: false